# Generated by Django 2.2.4 on 2019-08-21 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('highest_score', models.CharField(max_length=200)),
                ('lowest_score', models.CharField(max_length=200)),
                ('temp_question_range', models.IntegerField(default=0)),
                ('most_recent_quiz', models.CharField(default='', max_length=200)),
                ('date_done', models.DateTimeField(auto_now=True)),
                ('score_depo', models.CharField(max_length=10000)),
                ('RP', models.IntegerField(default=0)),
                ('total_question_answered', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
