# Generated by Django 2.2.4 on 2019-08-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_category',
            field=models.CharField(choices=[(1, 'basic user'), (2, 'advanced user'), (3, 'master user'), (4, 'basic admin')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
