# Generated by Django 2.2.4 on 2019-08-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_category',
            new_name='userCategory',
        ),
    ]
