# Generated by Django 2.2.4 on 2019-08-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190821_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userCategory',
            field=models.CharField(choices=[('1', 'basic user'), ('2', 'advanced user'), ('3', 'master user'), ('4', 'basic admin')], default='4', max_length=2),
        ),
    ]
