# Generated by Django 2.2.4 on 2019-08-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190821_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userCategory',
            new_name='category',
        ),
    ]
