# Generated by Django 2.2.4 on 2019-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190821_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('bu', 'basic user'), ('au', 'advanced user')], default='au', max_length=3),
        ),
    ]
