# Generated by Django 2.2.4 on 2019-08-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('bu', 'basic user'), ('au', 'advanced user'), ('mu', 'master user')], default='bu', max_length=3),
        ),
    ]
