# Generated by Django 2.2.4 on 2019-08-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190829_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
