# Generated by Django 2.2.4 on 2019-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190912_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingquestion',
            name='sender',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
