# Generated by Django 2.2.4 on 2019-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190915_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingquestion',
            name='answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
