# Generated by Django 2.2.7 on 2019-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191219_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_questions_list',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
