# Generated by Django 2.2.7 on 2019-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191220_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
