# Generated by Django 2.2.7 on 2019-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrong_questions',
            field=models.IntegerField(default=0),
        ),
    ]
