# Generated by Django 2.2.7 on 2020-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timeRange',
            field=models.CharField(default='', max_length=255),
        ),
    ]
