# Generated by Django 2.2.7 on 2020-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_timerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endtime',
            field=models.CharField(default='', max_length=255),
        ),
    ]
