# Generated by Django 2.2.7 on 2020-06-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_questions_list',
        ),
    ]
