# Generated by Django 2.1.7 on 2019-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
