# Generated by Django 2.1.7 on 2019-07-31 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
