# Generated by Django 2.1.7 on 2019-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190801_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_score',
            field=models.IntegerField(default=0),
        ),
    ]
