# Generated by Django 2.2.4 on 2019-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190804_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1l', '100 level'), ('2l', '200 level'), ('3l', '300 level'), ('4l', '400 level'), ('ot', 'others')], default='ot', max_length=5),
        ),
    ]
