# Generated by Django 2.2.4 on 2019-08-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190804_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Subject'),
        ),
    ]
