# Generated by Django 2.2.4 on 2019-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_myuser_temp_question_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='most_recent_quiz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
