# Generated by Django 2.2.4 on 2019-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_myuser_most_recent_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_done',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
