# Generated by Django 2.2.4 on 2019-08-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190814_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='last_score',
        ),
    ]
