# Generated by Django 2.2.4 on 2019-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_myuser_last_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='score_depo',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
