# Generated by Django 2.2.4 on 2019-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_myuser_lowest_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
