# Generated by Django 2.2.4 on 2019-08-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20190816_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='RP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='total_question_answered',
            field=models.IntegerField(default=0),
        ),
    ]
