# Generated by Django 2.2.4 on 2019-08-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20190818_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
