# Generated by Django 2.2.7 on 2019-12-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(max_length=10000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='RoyalEagle Team', editable=False, max_length=10)),
            ],
        ),
    ]
