# Generated by Django 2.2.17 on 2020-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_contest_rp_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
